# Generated by Django 3.1.2 on 2020-10-27 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_id', models.CharField(max_length=10, unique=True)),
                ('title', models.CharField(blank=True, max_length=2000)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('url', models.CharField(max_length=256, unique=True)),
                ('detail', models.CharField(max_length=10000)),
            ],
        ),
    ]
